version: "3"
services:
        client:
                image: paulehair/react-challenge-client
                restart: always
                ports:
                        - "80:80"
                working_dir: /home/node
                links: 
                        - api
                networks: 
                        - webappnetwork

        api:
                image: paulehair/react-challenge-server
                restart: always
                ports: 
                        - "9000:9000"
                working_dir: /usr/src/app
                depends_on: 
                        - mongodb
                networks: 
                        - webappnetwork
        
        mongodb: 
                image: mongo:3.2
                restart: always
                container_name: mongodb
                volumes: 
                        - ./data-node:/data/db
                ports: 
                        - "27017:27017"
                networks: 
                        - webappnetwork
                
networks:
        webappnetwork:
                driver: bridge
